@startuml HV Lo-Fi

skinparam Style StrictUML
skinparam LineType ortho
skinparam monochrome true

class Customer {
    * Customer_ID
--
    * First_Name
    * Surname
    * Phone_Number
    * Email_Address
    * Country
    Date of birth
    Music taste
}

class Product {
    * Product_ID
--
    * Product_Name
    * Product_Price
    * UnitsInStock
}

class Order {
    * Order_ID
--
    * Customer_ID
    * Shipping_Number
    * Shipping_Date
    * Gift wrapped?
}

class Shipping {
    * Shipping_Number
--
    * Shipping_Status
    * Shipping_Address
    * Shipping_Date
    * Shipping_City
    * Shipping_Country
}

class Payment_Details {
    * Payment_ID
--
    * Card_Number
    * CVV
    * Card_Expiry_Date
}

class Order_Details {
    * Order_ID
    * Product_ID
--
    * Product_Price
    * Quantity
}

class Cart {
    * Cart_ID
--
    * Customer_ID
}

class Cart_Item {
    * Cart_ID
    * Product_ID
--
    * Quantity
}

Customer ||--o{ Order
Customer ||-|| Cart
Cart ||-o{ Cart_Item
Cart_Item |o-|| Product
Payment_Details }|-|| Customer
Shipping ||-|{ Order
Order ||-|{ Order_Details
Order_Details }o-|| Product

@enduml