@startuml onlineshopping
actor :Registered\nCustomer: as RegisteredCustomer
actor :New\nCustomer: as NewCustomer
actor :Web\nCustomer: as WebCustomer

usecase (Search for music) as SearchForMusic
usecase (Browse music) as BrowseMusic
usecase (Add item to\nshopping cart) as AddItem
usecase (Modify shopping cart) as ModifyCart
usecase (Check out\nshopping cart) as Checkout 
usecase (Register Customer) as RegisterCustomer 
usecase (Collect customer's information) as CollectCustomerInformation
usecase (Check customer\nhas registered) as checkregister
usecase (Collect Shipping address) as CollectAddress
usecase (Collect Payment details) as CollectPayment
usecase (Check if items should\nbe gift wrapped) as GiftWrap
usecase (Log in) as Login

RegisteredCustomer --- Login
NewCustomer -- RegisterCustomer
RegisteredCustomer --- BrowseMusic
NewCustomer --- BrowseMusic
RegisteredCustomer --- SearchForMusic
NewCustomer --- SearchForMusic
AddItem .> Checkout : <<extend>>
SearchForMusic ...> AddItem : <<extend>>
BrowseMusic .> AddItem : <<extend>>
RegisteredCustomer -- ModifyCart 
NewCustomer -- ModifyCart
ModifyCart .> Checkout : <<extend>>
AddItem .> ModifyCart : <<extend>>
NewCustomer -- Checkout
RegisteredCustomer -- Checkout
WebCustomer ---|> RegisteredCustomer
WebCustomer ---|> NewCustomer
RegisterCustomer ..> CollectCustomerInformation : <<include>>
Checkout ..> checkregister : <<include>>
checkregister .> RegisterCustomer : <<extend>>
Checkout .> CollectAddress : <<include>>
CollectAddress .> GiftWrap : <<extend>>
Checkout ..> PaymentDetails : <<include>>

@enduml