@startuml shipping
actor :Staff: as Staff

usecase (Gift wrap items) as GiftWrap
usecase (Ship purchased\nitems) as ShipItems
usecase (Check items have been paid) as CheckItemsPaid
usecase (Check items are available) as CheckAvailability
usecase (Check if items should\nbe gift wrapped) as CheckGiftWrap
usecase (Order products from supplier) as ContactSupplier


Staff -- CheckAvailability
ShipItems <. CheckAvailability : <<extend>>
GiftWrap <. ShipItems : <<extend>>
CheckAvailability.> CheckItemsPaid : <<include>>
ShipItems ..> CheckGiftWrap : <<include>>
CheckAvailability ..> ContactSupplier : <<extend>>


@enduml