@startuml shipping
actor :Staff: as Staff
actor :Shipping Company: as shippingcompany

usecase (Gift wrap items) as GiftWrap
usecase (Ship purchased\nitems) as ShipItems
usecase (Check items have been paid) as CheckItemsPaid
usecase (Check items are available) as CheckAvailability
usecase (Check if items should\nbe gift wrapped) as CheckGiftWrap
usecase (Order products from supplier) as ContactSupplier
usecase (Process Order) as process


Staff -- CheckAvailability
ShipItems <. CheckAvailability : <<extend>>
GiftWrap <. ShipItems : <<extend>>
CheckAvailability.> CheckItemsPaid : <<include>>
ShipItems ..> CheckGiftWrap : <<include>>
CheckAvailability ..> ContactSupplier : <<extend>>
shippingcompany -- ShipItems
process -- Staff


@enduml